name: Auto Release

on:
  push:
    branches: [ "master" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Semantic Release
        id: semantic
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}

      - name: Clean up Old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
